'use client';

import { toSlug } from '@/lib/utils/slug';
import { useTranslation } from '../../../../lib/i18n-client';

interface CategorySlugPreviewProps {
  title: string;
}

export function CategorySlugPreview({ title }: CategorySlugPreviewProps) {
  const { t } = useTranslation();
  const slug = toSlug(title) || '—';

  return (
    <div>
      <span className="block text-sm font-medium text-gray-700 mb-1">
        {t('admin.categories.slug')}
      </span>
      <p className="rounded-md border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-600">
        {slug}
      </p>
      <p className="mt-1 text-xs text-gray-500">{t('admin.categories.slugAutoGenerated')}</p>
    </div>
  );
}
