/** Register page — shares login hero layout and form tokens. */

export {
  LOGIN_CENTER_COLUMN_CLASS as REGISTER_CENTER_COLUMN_CLASS,
  LOGIN_FORM_ACTIONS_CLASS as REGISTER_FORM_ACTIONS_CLASS,
  LOGIN_FORM_CARD_CLASS as REGISTER_FORM_CARD_CLASS,
  LOGIN_FORM_FIELD_GROUP_CLASS as REGISTER_FORM_FIELD_GROUP_CLASS,
  LOGIN_FORM_FIELDS_CLASS as REGISTER_FORM_FIELDS_CLASS,
  LOGIN_FORM_INPUT_CLASS as REGISTER_FORM_INPUT_CLASS,
  LOGIN_FORM_INPUT_SHELL_CLASS as REGISTER_FORM_INPUT_SHELL_CLASS,
  LOGIN_FORM_LABEL_CLASS as REGISTER_FORM_LABEL_CLASS,
  LOGIN_FORM_SHELL_CLASS as REGISTER_FORM_SHELL_CLASS,
  LOGIN_FORM_STACK_CLASS as REGISTER_FORM_STACK_CLASS,
  LOGIN_CHECKBOX_SQUARE_ICON_SRC as REGISTER_CHECKBOX_SQUARE_ICON_SRC,
  LOGIN_HEADING_STACK_CLASS as REGISTER_HEADING_STACK_CLASS,
  LOGIN_HERO_LEFT_CLIP_CLASS as REGISTER_HERO_LEFT_CLIP_CLASS,
  LOGIN_HERO_LEFT_COLUMN_CLASS as REGISTER_HERO_LEFT_COLUMN_CLASS,
  LOGIN_INPUT_EYE_OFF_ICON_SRC as REGISTER_INPUT_EYE_OFF_ICON_SRC,
  LOGIN_INPUT_LOCK_ICON_SRC as REGISTER_INPUT_LOCK_ICON_SRC,
  LOGIN_INPUT_MAIL_ICON_SRC as REGISTER_INPUT_MAIL_ICON_SRC,
  LOGIN_REMEMBER_ROW_CLASS as REGISTER_TERMS_ROW_CLASS,
  LOGIN_SECTION_DESKTOP_BLEED_CLASS as REGISTER_SECTION_DESKTOP_BLEED_CLASS,
  LOGIN_SECTION_STACK_CLASS as REGISTER_SECTION_STACK_CLASS,
  LOGIN_SIGNUP_FOOTER_CLASS as REGISTER_SIGNIN_FOOTER_CLASS,
  LOGIN_SIGNUP_LINK_CLASS as REGISTER_SIGNIN_LINK_CLASS,
  LOGIN_SUBMIT_BUTTON_CLASS as REGISTER_SUBMIT_BUTTON_CLASS,
  LOGIN_SUBTITLE_CLASS as REGISTER_SUBTITLE_CLASS,
} from '../login/login-page.constants';

/** First + last name row — contact-style two-column split. */
export const REGISTER_NAME_ROW_CLASS = 'grid grid-cols-1 gap-4 sm:grid-cols-2';

/** Terms copy — muted body with inline policy links. */
export const REGISTER_TERMS_TEXT_CLASS =
  'text-base font-medium leading-normal text-[#9c9c9c]';

export const REGISTER_TERMS_LINK_CLASS =
  'font-medium text-[#256dff] underline decoration-solid hover:text-[#1a52cc]';

export const REGISTER_PASSWORD_HINT_CLASS =
  'mt-1.5 text-sm leading-normal text-[#9c9c9c]';
